services:
  backend:
    build:
      context: ./backend # Build from backend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    # Add this to see more detailed logs
    command: sh -c "npm install && node index.js"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
