services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: yourname/blog-backend
    container_name: backend
    env_file:
      - ./backend/.env.prod
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "127.0.0.1:3001:3000" # <— only loopback, not public
