name: Deploy to VPS

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "nginx/**"
      - "docker-compose.prod.yml"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all files are available for rsync

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          script: |
            # Verify directory structure
            echo "Creating app directories..."
            mkdir -p ~/app/{backend,nginx,certbot}

            # Sync files with proper paths
            echo "Syncing backend files..."
            rsync -avz --delete \
              --exclude='.env' \
              --exclude='node_modules' \
              $GITHUB_WORKSPACE/backend/ ~/app/backend/

            echo "Syncing nginx files..."
            rsync -avz --delete $GITHUB_WORKSPACE/nginx/ ~/app/nginx/

            echo "Copying docker-compose file..."
            cp $GITHUB_WORKSPACE/docker-compose.prod.yml ~/app/docker-compose.yml

            # Docker operations
            echo "Starting containers..."
            cd ~/app
            docker compose down
            docker compose pull
            docker compose up -d --build

            # Wait for services to start
            echo "Waiting for services to initialize..."
            sleep 15

            # Run migrations
            echo "Running database migrations..."
            docker exec backend npm install  # Ensure dependencies exist
            docker exec backend npm run migrate
        env:
          GITHUB_WORKSPACE: /github/workspace # Explicitly set workspace path
          DOCKER_HOST: unix:///var/run/docker.sock
