name: Deploy Frontend to Vercel

on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/deploy.yml"

# ✅ Give the job rights to create a GitHub Deployment
permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.4"
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"

      # Optional: avoid pushing from CI. Create a lockfile locally if missing.
      - name: Ensure package-lock.json exists
        run: |
          if [ ! -f "client/package-lock.json" ]; then
            cd client
            npm i --package-lock-only
          fi

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Build client app
        run: npm run build
        working-directory: ./client

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          WORKING_DIRECTORY: ./client
          PRODUCTION: true
